code/PrimerDB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import RedirectView


urlpatterns = [
    url('primer/admin/', admin.site.urls),
    path('primer/', include('primer.urls')),
    path('', RedirectView.as_view(url='/primer/', permanent=False), name='index'),
    path('primer/users/', include('django.contrib.auth.urls')),
]

code/primer/urls.py
from django.urls import path
from . import views

app_name = 'primer'
urlpatterns = [
    path("back/", views.Back, name='backto'),
    path('',  views.PrimerView, name='primer'),
    path("<int:pk>/", views.DetailView, name='detail'),
    path('new/', views.NewEntryView, name="new"),
    path('<int:pk>/structure/', views.StructureView, name="structure"),
    path('primergroups/', views.PrimerGroupView, name="groups"),
    path('primergroupform/', views.PrimerGroupNew, name="groupform"),
    path("order/", views.OrderView, name='order'),
    path("orderhistory/", views.OrderHistoryView, name='orderhistory'),
    path("<int:pk>/orderhistory/", views.OrderHistoryFormView, name='orderhistoryform'),
    path("upload/", views.file_upload, name = "fileupload"),
    path("<name>/", views.Filtergroup, name='filtergroup'),
    path("mediafiles/<orderfile>/", views.file_download, name= 'download'),
]

code/primer/forms.py
from .models import Primer,PrimerGroup, OrderHistory
from django import forms
from django.forms.widgets import SelectDateWidget, FileInput
from datetime import date
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

def validator_excel(value):
    temp = str(value)
    if not temp.endswith("xls") or temp.endswith("xlsx"):
        raise ValidationError(
            _('Filetype must be Excel!')
        )

mod5 = open("staticfiles/primer/files/modification_5'.txt")
mod5 = [i.strip() for i in mod5.readlines()]
mod5_choices = zip(mod5, mod5)

mod3 = open("staticfiles/primer/files/modification_3'.txt")
mod3 = [i.strip() for i in mod3.readlines()]
mod3_choices = zip(mod3, mod3)


class OrderForm(forms.Form):
    list = forms.CharField(max_length=100000,widget=forms.HiddenInput())
    add = forms.CharField(max_length=6,widget=forms.HiddenInput())
    remove = forms.CharField(max_length=6,widget=forms.HiddenInput())


class PrimerForm(forms.ModelForm):
    # Adding dropdown with list of users
    createdby = forms.ModelChoiceField(queryset=User.objects.all(), label="Created by")
    notes = forms.CharField(widget=forms.Textarea, required=False)
    group = forms.ModelChoiceField(queryset=PrimerGroup.objects.all().order_by('groupnr'), label="Primer Group")
    mods5 = forms.ChoiceField(choices=mod5_choices, label="5' Modifications")
    mods3 = forms.ChoiceField(choices=mod3_choices, label="3' Modifications")
    lockrec = forms.BooleanField(label="Lock record", required=False)

    class Meta:
        model = Primer
        fields = (
        'oligonr', 'oligoname', 'sequence', 'scale', 'datefirst', 'createdby', 'group', "mods5",'mods3', 'templatetype',
        'application', 'storagelocation', 'notes','orderblockedforreview','datelast','tbo', 'ordered', 'lockrec')

        # Adding dropdown menu to Date of Order, with years ranging from 2001 to the current year
        widgets = {
            "datefirst": SelectDateWidget(years=tuple(range(date.today().year, 2000, -1)), attrs={"value": date.today}),
            'datelast': SelectDateWidget(years=tuple(range(date.today().year, 2000, -1)), attrs={"value": date.today}),
        }

class PrimerGroupForm(forms.ModelForm):
    class Meta:
        model= PrimerGroup
        fields = ('groupnr','name')

class OrderHistoryForm(forms.ModelForm):
    primers = forms.CharField(widget=forms.Textarea, required=False)
    PO_nr = forms.CharField(widget=forms.Textarea, required=False, label="PO Number")

    class Meta:
        model = OrderHistory
        fields = ('ordernr', 'PO_nr', 'orderdate', 'primers', 'orderfile')

        widgets = {
            "orderdate": SelectDateWidget(years=tuple(range(date.today().year, 2000, -1)), attrs={"value": date.today}),
        }

class UploadFileForm(forms.Form):
    file = forms.FileField(validators=[validator_excel])

code/primer/views.py
from django.db.models import Q
from django.contrib.postgres.search import SearchVector
from django.http import HttpResponse, HttpResponseRedirect
from .models import Primer, PrimerGroup, OrderHistory, validate_sequence
from .forms import PrimerForm, PrimerGroupForm, OrderForm, OrderHistoryForm, UploadFileForm
from django.shortcuts import render, redirect
from django.core.files import File
from .tables import PrimerTable, PrimerGroupTable, OrderTable, ExportTable, OrderHistoryTable
from django_tables2 import RequestConfig
import RNA
from pathlib import Path
import xml.etree.ElementTree as ET
import datetime
from django_tables2.export.export import TableExport
from cairosvg import svg2png
from django.contrib.auth.models import User
from datetime import date
import primer3
import pandas as pd
import os
from django.db import transaction, DatabaseError

##### FUNCTIONS #####

def Back(request):
    return redirect(os.environ['PRIMER_BACK'])


def search_request(request, search_vector):
    if "q" in request.GET and request.GET["q"]:
        q = request.GET["q"]
        datefrom = str(request.GET["from"])
        if datefrom == "":
            datefrom = "2000-01-01"
        datetill = str(request.GET["till"])
        if datetill == "":
            datetill = str(date.today())
        if "switch" in request.GET:
            switch = request.GET["switch"]
        else:
            switch = None

        # Searches for q in all specified columns
        # Differentiate between numbers and characters
        if q.isdigit():
            if switch != "ordered":
                qfloat = float(q)
                table = Primer.objects.filter(Q(scale=qfloat) & Q(
                    datefirst__range=[datefrom, datetill]) | Q(oligonr=qfloat) & Q(
                        datefirst__range=[datefrom, datetill]) | Q(melttemp = qfloat) & Q(
                        datefirst__range=[datefrom, datetill]) | Q(length = qfloat) & Q(
                        datefirst__range=[datefrom, datetill]) | Q(group = qfloat) & Q(
                        datefirst__range=[datefrom, datetill]))

            else:
                qfloat = float(q)
                table = Primer.objects.filter(Q(scale=qfloat) & Q(
                    datelast__range=[datefrom, datetill]) | Q(oligonr=qfloat) & Q(
                    datelast__range=[datefrom, datetill]) | Q(melttemp=qfloat) & Q(
                    datelast__range=[datefrom, datetill]) | Q(length=qfloat) & Q(
                    datelast__range=[datefrom, datetill]) | Q(group=qfloat) & Q(
                    datelast__range=[datefrom, datetill]))

        if not q.isdigit():
            if switch != "ordered":
                qlower = q.lower()
                table = Primer.objects.annotate(
                    search=search_vector).filter(Q(search__contains=qlower) & Q(
                    datefirst__range=[datefrom, datetill]) | Q(search=qlower) & Q(
                    datefirst__range=[datefrom, datetill]))
            else:
                qlower = q.lower()
                table = Primer.objects.annotate(
                    search=search_vector).filter(Q(search__contains=qlower) & Q(
                    datelast__range=[datefrom, datetill]) | Q(search=qlower) & Q(
                    datelast__range=[datefrom, datetill]))


        return q, table, datefrom, datetill, switch

    elif "q" in request.GET and request.GET["q"] == "":
        datefrom = str(request.GET["from"])
        datetill = str(request.GET["till"])

        if datefrom == "" and datetill == "":
            datetill = None
            datefrom = None
        else:
            if datefrom == "":
                datefrom = "2000-01-01"
            if datetill == "":
                datetill= str(date.today())

        q = None
        if "switch" in request.GET:
            switch = request.GET["switch"]
            if switch != "ordered":
                table = Primer.objects.filter(Q(datefirst__range=[datefrom, datetill]))
            else:
                table = Primer.objects.filter(Q(datelast__range=[datefrom, datetill]))
        else:
            switch = None
            table = Primer.objects.all()

        return q, table, datefrom, datetill, switch


def file_download(orderfile, filepath = "staticfiles/media/"):
    path_to_file = Path(filepath).joinpath(orderfile)
    f = open(path_to_file, 'rb')
    myfile = File(f)
    content = "vnd.ms-excel"
    if orderfile.endswith("pdf"):
        content = "pdf"
    response = HttpResponse(myfile, content_type='application/{}'.format(content))
    response['Content-Disposition'] = 'attachment; filename=' + orderfile
    return response


def file_upload(request):
    error = None
    form = UploadFileForm()

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            df_upload = pd.read_excel(request.FILES['file'], header=0)
            # CHECKS
            # check if provided template was used
            column_list = ['oligoname', 'sequence', "mods5", 'mods3', 'scale',
                           'templatetype', 'application', 'storagelocation', 'notes']
            missing_columns = [i for i in column_list if i not in df_upload.columns.values.tolist()]
            if len(missing_columns) > 0:
                error = "Please make sure to use the provided Excel template!"
                return render(request, 'primer/uploadview.html', {'form': form, 'error': error, 'missing': missing_columns})

            # check if any Primernames are already in Database
            exist_names = [i for i in df_upload["oligoname"].values.tolist() if i in Primer.objects.values_list("oligoname",flat=True)]
            if len(exist_names) > 0:
                error = "At least one Primer in the list already exists with the same name in the Database. Please change the name accordingly or check the Database!"
                return render(request, 'primer/uploadview.html', {'form': form, 'error': error, 'names': exist_names})

            # check if modifications are allowed
            mod5 = open("staticfiles/primer/files/modification_5'.txt")
            mod5 = [i.strip() for i in mod5.readlines()]
            mod3 = open("staticfiles/primer/files/modification_3'.txt")
            mod3 = [i.strip() for i in mod3.readlines()]

            if not all(x in mod5 for x in df_upload["mods5"].values.tolist()):
                error = "At least one 5' modification in the list does not comply with given modification list. A list of allowed 5' modifications can be found in the excel template!"
                return render(request, 'primer/uploadview.html', {'form': form, 'error': error})

            if not all(x in mod3 for x in df_upload["mods3"].values.tolist()):
                error = "At least one 3' modification in the list does not comply with given modification list. A list of allowed 3' modifications can be found in the excel template!"
                return render(request, 'primer/uploadview.html', {'form': form, 'error': error})

            # check if scale is correct
            if not all(x >= 0.001 for x in df_upload["scale"].values.tolist()):
                error = "At least one scale value in the list is smaller than 0.001. Please set it to a value higher than 0.001!"
                return render(request, 'primer/uploadview.html', {'form': form, 'error': error})

            # check for invalid characters
            allowed = ["A", "C", "G", "T", "*", "B", "D", "H", "K", "M", "N", "R", "S", "V", "W", "Y", "-"]
            for index, item in enumerate(df_upload["sequence"].values.tolist()):
                if not all(x in allowed for x in df_upload["sequence"][index]):
                    error = "Some characters in one of the sequences are not allowed. Allowed characters:" \
                            "A, C, G, T, *, B, D, H, K, M, N, R, S, V, W, Y, -"
                    return render(request, 'primer/uploadview.html', {'form': form, 'error': error})

            # WRITE
            # after initial checks, try to write into database
            try:
                with transaction.atomic(): # writing to database is one collective action
                    for i in range(0, len(df_upload)):
                        df_input = df_upload.loc[df_upload.index == i]
                        seq = df_input["sequence"][i]
                        if "-" in seq:
                            # melting temperature
                            df_input["melttemp"] = round(primer3.calcTm(seq.split("-")[1]), 2)
                        else:
                            df_input["melttemp"] = round(primer3.calcTm(seq), 2)

                        seq.replace("-","")

                        # SVG
                        ss, mfe = RNA.fold(seq)
                        # Creating temporary svg.file
                        filename = Path.cwd() / "tmp.svg"
                        RNA.svg_rna_plot(seq, ss, str(filename))
                        # Resizing svg to 100x100px to fit table by replacing code
                        with open(filename, "rb") as f:
                            svg = _add_view_box(f.read(), 100, 100)
                        # Deletion of temporary svg.file
                        filename.unlink()
                        df_input["secstruc"] =  svg

                        # ENTRY INTO DATABASE
                        newprimer = Primer(createdby= request.user, datefirst = date.today(), datelast = None, orderblockedforreview = False,
                                           tbo = False, ordered = False, lockrec = False, purification = "Desalt", format = "Dry")
                        newprimer.oligoname = df_input["oligoname"][i]
                        newprimer.sequence = df_input["sequence"][i].upper()
                        newprimer.mods5 = df_input["mods5"][i]
                        newprimer.mods3 = df_input["mods3"][i]
                        newprimer.scale = df_input["scale"][i]

code/primer/templates/primer/orderhistoryview.html
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" type="text/css" href="{% static 'primer/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <meta charset="UTF-8">
    <title>Order History</title>
    <h1 align="center" style="font-family: verdana; font-size: 40px">Order History</h1>
</head>

<body>
<br>
<div align="center" style=" color: white; font-weight: bold">
    <button style="font-size: 15px; width: 100px" title="Go to Primers"
            onclick="location.href='{% url 'primer:primer' %}'">PRIMERS
    </button>
    <button style="font-size: 15px; width: 100px" title="Go to OrderView"
            onclick="location.href='{% url 'primer:order' %}'">ORDER
    </button>
    <button style="font-size: 15px; color: white; font-weight: bold; margin-right: 5px;width: 100px" title="Export to Excel"
            onclick="location.href='{% querystring '_export'='xls' %}'">EXPORT
    </button>
</div>
<br><br>

{% if q != None or datefrom != None or datetill != None %}
    <div align="center">
        <div style="border: 1px solid; display: inline-block; padding-left: 20px; padding-right: 20px;">
            {% if q != None %}
                <h3 align="center">Showing results for: {{ q }}</h3>
            {% endif %}
            {% if datefrom != None and datefrom != "2000-01-01" %}
            <h3 align="center">From: {{ datefrom }}</h3>
            {% endif %}
            {% if datetill != None and datetill != today %}
            <h3 align="center">Till: {{ datetill }}</h3>
            {% endif %}
        </div>
    </div>
<br>
{% endif %}

<form method="get" action="">
    <base href="/primer/orderhistory"/>
    <img title="Search options" onclick="options()"
         style="float: left; height: 28px; width: 28px;margin-right:5px; margin-left:5px; cursor:pointer"
         src="{% static 'primer/images/cog.png' %}" id="cogwheel">
    <input type="search" name="q" placeholder="Search..." style="float: left; height: 30px" size="55">

    <button title="Fields searched:
Order Number, PO Number, Amount of Primers, Ordered Primers"
            type="submit" style="float: left; width: 100px;color:white;font-weight: bold;"> SEARCH
    </button>
    <button title="Clear search" type="button" onclick="location.href='{% url 'primer:orderhistory' %}'"
            style="float: left; width: 100px;color:white; font-weight: bold;">
        CLEAR
    </button>
    <br><br>
    <div id="optionsdatefirst" style="background-color:lightgray; width: 350px;height:120px;display:none; align:center">
        <br>
        <label style="font-size:16px; color:red; margin-left:10px"><u>Date of Order</u></label>

        <br>
        <label id="labelfrom" for="from" style="margin-left:10px">Date from:</label><input id="from" type="date" name="from"
                                                                  placeholder="From..." size="20" style="margin-left:10px">
        <br>
        <label id="labeltill" for="till" style="margin-left:10px">Date till:</label><input id="till" type="date" name="till"
                                                                  placeholder="Till..." size="20" style="margin-left:25px">
    </div>
</form>

<button id="topbtn"  onclick="topFunction()" title="Go to top">TOP &#8657</button>

{% render_table table %}
</body>


<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}">
</script>

<script>
    <!--Toggle to show options-->
    function options() {
        var x = document.getElementById("optionsdatefirst");
        var z = document.getElementById("optionsdatelast");
        if (x.style.display === "none") {
            x.style.display = "block";
            z.style.display = "block";
        } else {
            x.style.display = "none";
            z.style.display = "none";
        }
    };

    function toggle1() {
        var x = document.getElementById("created");
        var y = document.getElementById("ordered");
        if (x.checked === true) {
            document.getElementById("from").style.visibility = "visible";
            document.getElementById("till").style.visibility = "visible";
            document.getElementById("labelfrom").style.visibility = "visible";
            document.getElementById("labeltill").style.visibility = "visible";
            y.checked = false;
        } else if (y.checked === false && x.checked === false) {
            document.getElementById("from").style.visibility = "hidden";
            document.getElementById("till").style.visibility = "hidden";
            document.getElementById("labelfrom").style.visibility = "hidden";
            document.getElementById("labeltill").style.visibility = "hidden";
        }
    };

            window.onscroll = function() {scrollFunction()};

    function scrollFunction() {
      if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("topbtn").style.display = "block";
      } else {
        document.getElementById("topbtn").style.display = "none";
      }
    }

    // When the user clicks on the button, scroll to the top of the document
    function topFunction() {
      document.body.scrollTop = 0; // For Safari
      document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
    };

</script>
</html>

code/primer/templates/primer/tableview.html
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Oligo Primer Database</title>

    <link rel="stylesheet" type="text/css" href="{% static 'primer/css/style.css' %}">
    <div class="row">
        <div class="col-md-1"><a href="mailto:alex.benkoe@hotmail.com?subject=Oligo Primer Database">
            <img class="logo" src="{% static 'primer/images/OligoPrimerLogo.png' %}"
                 onclick="location.href='{% url 'primer:primer' %}"
                 alt="Created by: Alexander Benkö"
                 title="Created by: Alexander Benkö"/></a>
        </div>
        <div class="col-md-5"><h1 class="headline" onclick="location.href='{% url 'primer:primer' %}'"
                                  style="cursor:pointer">Oligo Primer Database</h1></div>
    </div>

    {% if q != None or errmsg != "" or datefrom != None or datetill != None or switch != None %}
    <div align="center">
        <div style="border: 1px solid; display: inline-block; padding-left: 20px; padding-right: 20px;">
            {% if q != None and errmsg == "" %}
                <h3 align="center">Showing results for: {{ q }}</h3>
            {% endif %}
            {% if datefrom != None and datefrom != "2000-01-01" %}
            <h3 align="center">From: {{ datefrom }}</h3>
            {% endif %}
            {% if datetill != None and datetill != today %}
            <h3 align="center">Till: {{ datetill }}</h3>
            {% endif %}
             {% if switch != None %}
            <h3 align="center">By: {{ switch }}</h3>
            {% endif %}
            {% if errmsg != "" %}
                <h2 align="center">{{ errmsg }}</h2>
            {% endif %}
        </div>
    </div>
    {% endif %}

    {% if user.is_superuser %}
        <a style="margin-left:6px; margin-right: 6px; font-size:16px" href="{% url 'admin:index' %}">Admin Panel</a>
        |
    {% endif %}
    <a style="margin-left:6px; margin-right: 6px; font-size:16px" href="{% url 'primer:backto' %}">IMICS</a>
     |
    {% if user.is_authenticated %}
        <a style="margin-left:6px; margin-right: 6px;font-size:16px" href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a style="margin-left:6px; margin-right: 6px;font-size:16px" href="{% url 'logout' %}">Login</a>
    {% endif %}



    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>

</head>
<body>
<div class="sticky">
    <form method="get" action="">
        <base href="/primer/"/>
        <img title="Search options" onclick="options()"
             style="float: left; height: 28px; width: 28px;margin-right:5px; margin-left:5px; cursor:pointer; background-color: white"
             src="{% static 'primer/images/cog.png' %}" id="cogwheel">
        <input type="search" name="q" placeholder="Search..." style="float: left; height: 30px" size="55">

        <button title="Fields searched:
Oligo Nr, Oligo Name, Sequence, Length, Melting Temp, Modifications 5', Modifications 3', Scale, Created by, Group, Template type, Application, Storage Location"
                type="submit" style="float: left; width: 100px;color:white;font-weight: bold;"> SEARCH
        </button>
        <button title="Clear search" type="button" onclick="location.href='{% url 'primer:primer' %}'"
                style="float: left; width: 100px;color:white; font-weight: bold;">
            CLEAR
        </button>
        <br><br>
        <div class="row">
            <div class="col-md-1" id="options"
                 style="background-color:lightgray; width: 350px;height:220px;display:none">
                <br>
                <label style="font-size:16px; color:red"><u>Check fields to exclude from textsearch:</u></label>
                <br>
                <input class="firstbox" type="checkbox" name="oligoname" value="f"/><label class="firstlbl">Oligo
                Name</label>
                <input class="secbox" type="checkbox" name="sequence" value="f"/><label class="seclbl">Sequence</label>
                <br>
                <input class="firstbox" type="checkbox" name="mods5" value="f"/><label class="firstlbl">Modifications
                5'</label>
                <input class="secbox" type="checkbox" name="mods3" value="f"/><label class="seclbl">Modifications
                3'</label>
                <br>
                <input class="firstbox" type="checkbox" name="createdby" value="f"/><label class="firstlbl">Created
                by</label>
                <input class="secbox" type="checkbox" name="templatetype" value="f"/><label class="seclbl">Template
                type</label>
                <br>
                <input class="firstbox" type="checkbox" name="application" value="f"/><label class="firstlbl">Application</label>
                <input class="secbox" type="checkbox" name="storagelocation" value="f"/><label class="seclbl">Storage
                location</label>
                <br>
                <input class="firstbox" type="checkbox" name="notes" value="f"/><label class="firstlbl">Notes</label>
                <br><br>
            </div>
            <div class="col-md-8" id="optionsdatefirst"
                 style="background-color:lightgray; width: 180px;height:220px;display:none">
                <br>
                <input type="checkbox" name="switch" id="created" value="created" onchange="toggle1()">
                <label style="font-size:16px; color:red"><u>Range Created</u></label>
                <br>
                <input type="checkbox" name="switch" id="ordered" value="ordered" onchange="toggle2()">
                <label style="font-size:16px; color:red"><u>Range Ordered</u></label>
                <br>
                <label id="labelfrom" style="visibility: hidden" for="from">Date from:</label><input
                    style="visibility: hidden" id="from" type="date" name="from" placeholder="From..." size="20">
                <br>
                <label id="labeltill" style="visibility: hidden" for="till">Date till:</label><input
                    style="visibility: hidden" id="till" type="date" name="till" placeholder="Till..."
                    style="float: left" size="20">
            </div>
        </div>
    </form>
</div>

<div class="sticky" style="color:white; font-weight: bold;">
    <img title="Help" onclick="location.href='{% querystring 'download'='help' %}'"
         style="height: 28px; width: 28px;margin-right:5px; margin-left:5px; cursor:pointer; float:right"
         src="{% static 'primer/images/questionmark.png' %} " id="questionmark">
    <form>
        <button style="float: right;width: 100px;font-size: 15px" title="Go to NCBI/Primer Blast"
                formaction="https://www.ncbi.nlm.nih.gov/tools/primer-blast/index.cgi?LINK_LOC=BlastHome"
                formtarget="_blank">BLAST
        </button>
    </form>
 {% if user.is_superuser %}
    <button style="float: right;font-size: 15px; width: 100px" title="Upload Primers into Database"
            onclick=upload()>UPLOAD
    </button>
    {% endif %}
    <button style="float: right;font-size: 15px; width: 100px" title="Go to Primer Groups"
            onclick="location.href='{% url 'primer:groups' %}'">GROUPS
    </button>
    {% if user.is_superuser %}
        <button style="float: right;font-size: 15px; width: 100px" title="Go to Order View"
                    onclick="location.href='{% url 'primer:order' %}'">ORDER
        </button>
    {% endif %}
    <button style="float: right;font-size: 15px;width: 100px" title="Export to Excel"
            onclick="location.href='{% querystring '_export'='xls' %}'">EXPORT
    </button>
    <button style="float: right; width: 100px;font-size: 15px" title="Add new entry"
            onclick="location.href='{% url 'primer:new' %}'">NEW
    </button>
</div>

<button id="topbtn"  onclick="topFunction()" title="Go to top">TOP &#8657</button>

{% render_table table %}

    <!-- Version Number -->
  <p id="version" style="float: right;"><i>Version: 1.0</i></p>

</body>

<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}">
</script>

<script>
 <!--Toggle to show options-->
function options() {
  var x = document.getElementById("options");
  var y = document.getElementById("optionsdatefirst");
  var z = document.getElementById("optionsdatelast");
  if (x.style.display === "none") {
    x.style.display = "block";
    y.style.display = "block";
    z.style.display = "block";
  }else{
    x.style.display = "none";
    y.style.display = "none";
    z.style.display = "none";
  }
};

function toggle1() {
    var x = document.getElementById("created");
    var y = document.getElementById("ordered");
    if (x.checked === true) {
        document.getElementById("from").style.visibility = "visible";
        document.getElementById("till").style.visibility = "visible";
        document.getElementById("labelfrom").style.visibility = "visible";
        document.getElementById("labeltill").style.visibility = "visible";
        y.checked = false;
    } else if (y.checked === false && x.checked === false) {
        document.getElementById("from").style.visibility = "hidden";
        document.getElementById("till").style.visibility = "hidden";
        document.getElementById("labelfrom").style.visibility = "hidden";
        document.getElementById("labeltill").style.visibility = "hidden";
    }
};

function toggle2() {
    var x = document.getElementById("created");
    var y = document.getElementById("ordered");
    if (y.checked === true) {
        document.getElementById("from").style.visibility = "visible";
        document.getElementById("till").style.visibility = "visible";
        document.getElementById("labelfrom").style.visibility = "visible";
        document.getElementById("labeltill").style.visibility = "visible";
        x.checked = false;
    } else if (y.checked === false && x.checked === false) {
        document.getElementById("from").style.visibility = "hidden";
        document.getElementById("till").style.visibility = "hidden";
        document.getElementById("labelfrom").style.visibility = "hidden";
        document.getElementById("labeltill").style.visibility = "hidden";
    }
};
    function upload() {
      var myWindow = window.open("{% url 'primer:fileupload' %}", "", "width=500,height=500");
    };

        window.onscroll = function() {scrollFunction()};

    function scrollFunction() {
      if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("topbtn").style.display = "block";
      } else {
        document.getElementById("topbtn").style.display = "none";
      }
    }

    // When the user clicks on the button, scroll to the top of the document
    function topFunction() {
      document.body.scrollTop = 0; // For Safari
      document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
    };
</script>
</html>